<?php

namespace Teamate\GymBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PitchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PitchRepository extends EntityRepository
{
}
