<?php

namespace Teamate\GymBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * sportcenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sportcenterRepository extends EntityRepository
{
}
