<?php

namespace Teamate\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * demandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demandRepository extends EntityRepository
{
}
