<?php

namespace Teamate\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchplaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchplaceRepository extends EntityRepository
{
}
