parameters:
#    teamate_gym.example.class: Teamate\GymBundle\Example

services:
#    teamate_gym.example:
#        class: %teamate_gym.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
