teamate_match_homepage:
    pattern:  /Matches
    defaults: { _controller: TeamateMatchBundle:Default:index }

game:
    type: rest
    resource: Teamate\MatchBundle\Controller\GameController

teamate_match_create:
    pattern:  /creer_mon_match
    defaults: { _controller: TeamateMatchBundle:Default:create }