parameters:
#    teamate_user.example.class: Teamate\UserBundle\Example

services:
#    teamate_user.example:
#        class: %teamate_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
