<?php

namespace Rc\TeamateBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getLastGames($number = 3)
    {
        $qb = $this->createQueryBuilder('b')
            ->orderBy('b.created_at', 'DESC')
            ->setMaxResults($number);


        $query = $qb->getQuery();

        return $query->getResult();
    }
}
